name: "Download external data everyday"

on:
  workflow_dispatch:
  schedule:
    -   cron: "0 0 * * *"

jobs:
  export-jpegs:
    runs-on: ubuntu-latest
    name: Export JPEGs
    timeout-minutes: 60
    steps:
      -   uses: actions/checkout@v4
          with:
            token: ${{ secrets.GH_TOKEN }}
            fetch-depth: 0
      -   name: Remove old data
          run: |
            if [ -d external ] && [ "$(ls -A external)" ]; then
                rm external/*
                echo "Files removed from 'external'."
            elif [ -d external ]; then
                echo "Directory 'external' is empty. Nothing to remove."
            else
                echo "Directory 'external' does not exist. Skipping removal."
            fi
      -   name: Set up Python 3.12
          uses: actions/setup-python@v2
          with:
            python-version: 3.12
      -   name: Setup dependencies
          run: pip install -r requirements.txt
      -   name: Download external images
          run: python utils.py
      - run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add .
          git commit --amend --no-edit
          git push --force-with-lease
