name: "Update stock data everyday"

on:
  workflow_dispatch:
  schedule:
    -   cron: "30 4 * * *"
    -   cron: "00 8 * * *"

jobs:
  export-jpegs:
    runs-on: ubuntu-latest
    name: Export JPEGs
    timeout-minutes: 60
    steps:
      -   uses: actions/checkout@v4
          with:
            token: ${{ secrets.GH_TOKEN }}
            fetch-depth: 0
      -   name: Set up Python 3.12
          uses: actions/setup-python@v2
          with:
            python-version: 3.12
      -   name: Setup dependencies
          run: pip install -r requirements.txt
      -   name: Remove old jpg
          run: rm images/*
      -   name: Remove old data
          run: rm data/*
      -   name: Run export jpg
          run: python main.py
      - run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add .
          git commit --amend --no-edit
          git push --force-with-lease
